In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
data=pd.read_csv("C:/Users/manch/Downloads/data.csv")

In [3]:
data.head()

,datetime,open,high,low,close,volume,reserve,funding_rates,mvrv,nrpl,nupl,stock_to_flow_reversion,sth_sopr,signal,RSI,9_ema,21_ema,50_ema,200_ema,Fear_and_Greed_Index
0,2020-07-16,9190.80,9216.02,9005.00,9130.11,8765.698589,2.889262e+06,0.009332,1.563972,-3.694023e+06,0.360602,0.421011,0.997131,none,47.108800,9214.535081,9196.119258,9524.945856,9671.528810,43
1,2020-07-17,9130.93,9182.99,9054.99,9154.29,6423.747162,2.889943e+06,0.007262,1.568555,3.367513e+05,0.362471,0.366354,0.999726,none,48.843088,9202.486065,9206.292278,9560.413230,9718.271795,41
2,2020-07-18,9154.29,9210.00,9122.65,9175.85,4121.626974,2.890642e+06,0.004125,1.572507,7.637219e+06,0.364073,0.404649,1.000724,buy,50.404638,9197.158852,9216.465298,9595.880603,9765.014781,44
3,2020-07-19,9175.83,9245.03,9105.37,9212.87,3520.072476,2.892067e+06,0.007809,1.579355,2.053120e+07,0.366830,0.409607,1.000859,none,53.054470,9200.301081,9226.638318,9631.347977,9811.757766,41
4,2020-07-20,9214.01,9223.51,9131.00,9161.05,5815.330842,2.891858e+06,0.010244,1.568483,7.103351e+06,0.362441,0.437860,1.000647,none,49.099864,9192.450865,9236.811338,9666.815351,9858.500751,44

In [4]:
data.tail()

,datetime,open,high,low,close,volume,reserve,funding_rates,mvrv,nrpl,nupl,stock_to_flow_reversion,sth_sopr,signal,RSI,9_ema,21_ema,50_ema,200_ema,Fear_and_Greed_Index
930,2023-02-01,23127.15,23813.57,22760.00,23735.97,20292.224170,2.228658e+06,0.010046,1.197895,3.665064e+08,0.165202,1.053647,1.043648,none,73.827696,23052.123348,21916.623693,20118.284733,21237.270436,56
931,2023-02-02,23735.97,24262.18,23367.87,23493.84,16368.921383,2.225632e+06,0.017552,1.185242,1.677386e+08,0.156290,1.103838,1.027135,none,70.357821,23140.466679,22060.006994,20250.659449,21259.723865,60
932,2023-02-03,23497.29,23720.00,23208.01,23433.54,14215.668430,2.221115e+06,0.012482,1.181964,1.003611e+08,0.153951,1.009916,1.021413,none,69.481991,23199.081343,22184.873631,20375.478294,21281.353876,60
933,2023-02-04,23433.47,23589.67,23257.71,23328.87,3567.130075,2.219863e+06,0.007240,1.176299,1.410151e+08,0.149876,1.028088,1.028341,none,67.901909,23225.039074,22288.873301,20491.297577,21301.727171,58
934,2023-02-05,23329.47,23433.20,22758.01,22936.34,6536.140584,2.222216e+06,0.003896,1.156946,3.282193e+06,0.135655,1.130099,1.007593,none,62.190221,23167.299260,22347.733910,20587.181593,21317.991975,58

In [5]:
data.shape

(935, 20)

In [6]:
data.describe()

,open,high,low,close,volume,reserve,funding_rates,mvrv,nrpl,nupl,stock_to_flow_reversion,sth_sopr,RSI,9_ema,21_ema,50_ema,200_ema,Fear_and_Greed_Index
count,935.000000,935.000000,935.000000,935.000000,935.000000,9.350000e+02,935.000000,935.000000,9.350000e+02,935.000000,935.000000,935.000000,935.000000,935.000000,935.000000,935.000000,935.000000,935.000000
mean,32854.990235,33748.030417,31841.441326,32869.649166,19776.787469,2.655477e+06,0.010833,1.887077,2.638039e+08,0.364061,1.587759,1.005996,52.406224,32810.048490,32729.191448,32582.628701,32110.411317,45.706952
std,15586.619424,16026.828089,15051.951866,15570.876889,12739.460780,1.542206e+05,0.023959,0.773880,9.690276e+08,0.282549,0.797501,0.031463,14.396264,15497.199601,15382.324826,14982.202215,12293.601467,25.749944
min,9130.930000,9182.990000,9005.000000,9130.110000,3211.704593,2.214551e+06,-0.116700,0.759394,-4.302549e+09,-0.316839,0.366354,0.866222,20.285894,9192.450865,9196.119258,9524.945856,9671.528810,6.000000
25%,19239.850000,19554.870000,18850.245000,19258.600000,11166.544857,2.596823e+06,-0.000010,1.172578,-1.718159e+08,0.147169,0.905744,0.989412,41.382874,19322.981514,19417.071530,19207.403858,21255.649974,24.000000
50%,33077.430000,34231.540000,31432.190000,33080.660000,16961.108288,2.689092e+06,0.005040,1.806507,6.615847e+07,0.446445,1.483322,1.000418,50.496180,33560.442757,33620.120486,34805.448787,34449.423397,39.000000
75%,45709.475000,47058.655000,44145.240000,45705.135000,24086.969086,2.753680e+06,0.012384,2.382392,4.871924e+08,0.580254,2.219189,1.018265,61.468009,45330.585351,44958.719425,44505.259597,42075.874387,72.000000
max,67554.130000,69000.000000,66261.790000,67554.840000,119633.961941,2.947289e+06,0.154037,3.981206,5.863688e+09,0.748820,3.805708,1.193530,89.347312,64490.167763,63062.412439,59135.220214,50120.543237,95.000000

In [7]:
data.columns

Index(['datetime', 'open', 'high', 'low', 'close', 'volume', 'reserve',
       'funding_rates', 'mvrv', 'nrpl', 'nupl', 'stock_to_flow_reversion',
       'sth_sopr', 'signal', 'RSI', '9_ema', '21_ema', '50_ema', '200_ema',
       'Fear_and_Greed_Index'],
      dtype='object')

In [8]:
data.nunique()

datetime                   935
open                       935
high                       930
low                        928
close                      935
volume                     935
reserve                    935
funding_rates              935
mvrv                       935
nrpl                       935
nupl                       935
stock_to_flow_reversion    935
sth_sopr                   935
signal                       3
RSI                        935
9_ema                      935
21_ema                     935
50_ema                     935
200_ema                    935
Fear_and_Greed_Index        84
dtype: int64

In [9]:
data.isnull().sum()

datetime                   0
open                       0
high                       0
low                        0
close                      0
volume                     0
reserve                    0
funding_rates              0
mvrv                       0
nrpl                       0
nupl                       0
stock_to_flow_reversion    0
sth_sopr                   0
signal                     0
RSI                        0
9_ema                      0
21_ema                     0
50_ema                     0
200_ema                    0
Fear_and_Greed_Index       0
dtype: int64

In [11]:
corelation=data.corr()

ValueError: could not convert string to float: '2020-07-16'